edition = "2021"
group_imports = "StdExternalCrate"
imports_granularity = "Module"
newline_style = "Unix"
normalize_comments = true
unstable_features = true
use_field_init_shorthand = true
style_edition = "2024"
